### ISSUE TITLE
あびやログで投稿内容が欄右端で折り返されない

### ISSUE THREAD

**Issue by venuswink** [tomokusaba/BlazorServerChat2#6]
Firefox/Linux での現象ですが、あびやログの投稿内容欄で、欄の幅を超える長い文が右端で折り返されず、テキストボックスのスクロールもできないので、欄の幅を超えた部分が読めません。

**Comment by tomokusaba** [comment]
UIフレームワークをFluentUIに根本的に入れ替えることを計画中です。

**Comment by tomokusaba** [comment]
たぶん、これで大丈夫

**Comment by venuswink** [comment]
ログでの折返しは確認しました。
